# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

#pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2'
#pod 'SDWebImage', '~> 4.0.0'
#pod 'MJRefresh', '~> 3.1.12'
#pod 'UMengAnalytics'
#pod 'FMDB', '~> 2.6.2'
#pod 'IQKeyboardManager'

#end
